/**
 * @author Rohit Alladi
 * @date Feb 2019
 * @group Exception Helper Classes
 * @group-content ../ApexDocContent/Classes.html
 * @description Constants for Exception Helper
 **/
public class EXH_Constants {

    public static final String DFLT_FRIENDLY_ERR_MSG = 'Oops! Sorry, something unexpected happened. Please tell your administrator.';
    public static String LOCALE_EN_US = 'en_US';
    public static final String PROFILE_SYSTEM_ADMIN = 'System Administrator';
}